examples/06.Synthesis/AMsynth/AMsynth.ino
examples/06.Synthesis/AMsynth_HIFI/AMsynth_HIFI.ino

Case sensitive filesystems (as on Linux) won't find COS2048_int8.h, but will work with cos2048_int8.h

Case correction on examples

---

MozziGuts.h

This patch removes two warnings that are shown on compiling (almost) every Mozzi sketch.
The first is about redefinition of CONTROL_RATE. The documentation states that this can be overridden, explicitly, but the compiler will still generate a warning in this case. The patch removes the warning - if, and only if - CONTROL_RATE is defined _before_ including MozziGuts.h. If control rate is defined _after_ including MozziGuts.h, a warning will still be generated, but the behavior will continue to be just as before.
The second part of the sketch removes the unconditional warning about the audio setup. I understand these warnings were added, intentionally, and probably for good reason. However, having them around all of the time is a distraction from "real" warnings: Once you get used to the …

Silence some warnings

---

ADSR.h

On further thought, you are absolutely right: Going back to zero level on noteOn(), _unconditionally_, is not desirable. For "normal" note amplitude envelopes, it will be best to continue from the current level, if a note is re-triggered while still playing (esp. during release). However, for other use cases of envelopes (effect envelopes), going back to zero may be much more desirable.
So the new attempt leaves the choice to the user, with explicit documentation.

New attempt: Allow to force an ADSR envelope back to zero on noteOn().

---

ADSR.h
AudioConfigSTM32.h
EventDelay.h
Line.h
MozziGuts.cpp
MozziGuts.h
MultiLine.h
MultiLine2.h
Oscil.h
Phasor.h
README.md
Sample.h
SampleHuffman.h
StateVariable.h

Ok, this one is definitely just a discussion starter, rather than a real pull request. It works for me, beautifully, on both STM32 and a Pro Mini, but it's clearly a non-trivial change. Also, if you were to give the go-ahead to this one, it would mean that _a lot_ of code can be removed (everything about Timer 0, essentially).
But to start at the beginning: The starting point to this idea was that I was struggling with some IO latency issues while handling MIDI file playback (see http://www.stm32duino.com/viewtopic.php?f=19&t=3041&sid=dc7ca666b2b92884cde768b1f4de1728). In that context I began thinking about what parts of the processing I could move from updateControl() to the main loop. But then, I started wondering, why isn't updateControl() part of the main loop in the first place? …

Trigger updateControl from within audioHook(), rather than from timer.

---

AutoRange.h

This following two fixes are contained in this PR:
1. Fixed an obvious bug in the initialization of AutoRange.
The max_expected and min_expected values were initialized, firstly in
the wrong order, and secondly the calling parameters were swapped,
causing the AutoRange::max_expected to be initialized to min_expected
and AutoRange::min_expected to be initialized to max_expected.
2. Fixes the overwriting of the original min and max ranges.
The original max_expected and min_expected values were overwritten,
causing the expected range to change and produced inconsistent return
values from AutoRange::next().

Fixed AutoRange::AutoRange initialization and AutoRange::next behavior.

---

AutoRange.h

Reverts sensorium/Mozzi#56
The intended behaviour is to continually adjust range_max and range_min if incoming values lie outside the ranges.  The proposed change would only have updated max and min when they exceed the initialised values, instead of allowing them to grow each time they are exceeded.

Revert "Fixed AutoRange::AutoRange initialization and AutoRange::next behavior."

---

ADSR.h
Line.h

Hi!
This corrects the fact that, when using very small values for the release time, the envelop may start, for a new note, on a non-zero value.
I think, even though the envelop is effectively reaching 0 at the end, the last point of the line (transition) used to interpolate points between sustain value do not reach zero and its last value is used for starting the envelop.
Note: this has been for very short (<20 micro) on STM32. Did not try to reproduce on AVR but I do not see why it would behave differently.
Sincerely,
T. Combriat

Corrected wrong behavior leading to a wrong value of the starting point of the envelop when using very small values for the release time

---

examples/13.External_Audio_Output/FMsynth_MCP4921_mono_12bits/FMsynth_MCP4921_mono_12bits.ino
examples/13.External_Audio_Output/MCP4922_mono_24bits/MCP4922_mono_24bits.ino
examples/13.External_Audio_Output/Stereo_Pan_MCP4922_stereo_12bits/Stereo_Pan_MCP4922_stereo_12bits.ino

Hi,
This provides examples for using SPI DAC MCP49XX or MCP48XX with Mozzi, using the `audioOutput` function.
Three examples are provided:
- FMsynth_MCP4921_mono_12bits is a simple mono 12 bits based on the FM example,
- Stereo_Pan_MCP4922_stereo_12bits is a simple stereo 12 bits, using Stereo_Hack,
- MCP4922_mono_24bits is a simple mono 24 bits, using the same technique than the HiFi mode of Mozzi.
- I had to modify the library I was using to provide support for non-AVR platform. The modified library is available [here](https://github.com/tomcombriat/DAC_MCP49XX) (this is written in the sketches)
- All examples work with STM32 board
- First example works fine on Arduino Mega, but the second is not so smooth. I think there is a compatibility problem between the Mega and the PortWrite …

Added examples using DAC MCP49XX/48XX with Mozzi

---

ADSR.h
examples/07.Envelopes/ADSR_Audio_Rate_Envelope_Long/ADSR_Audio_Rate_Envelope_Long.ino

Hi!
This adds a third template parameter to the ADSR, affecting the update steps.
It allows to create long envelopes at AUDIO_RATE as the `unsigned int` initially used can be replaced by `unsigned long` for instance; the initial implementation does not allow ADSR longer than 3.6s (if my memory is correct) at AUDIO_RATE. This reduces performances on AVR, but does not affect native 32bits platforms like STM32 or ESP.
A default parameter (`unsigned int`) is specified thus, this does not change the behavior of existing sketches.
An example, basically copy pasted from an existing one, with small adaptations is also added.
Let me know if you have any comments!
Best,

Added a third template parameter to ADSR to allow long envelopes at AUDIO_RATE

---

AudioConfigESP32.h
MozziGuts.cpp
MozziGuts.h
hardware_defines.h
mozzi_analog.cpp
mozzi_config.h
mozzi_pgmspace.h

Optional choices for PT8211 DAC and internal DAC in mozzi_config.h, though internal DAC is buggy. 
I have a working solution for internal DAC based on the Mozzi version from around january 2020, because that's what zcarlos's solution in the google forum was built on. I fixed that to work better. However when I port those I2S settings to the current version of Mozzi I get a chopped up signal that I can't get into shape by bitshifting ranges, which helped before.  
PT8211 works, though I am unsure whether timing of sample calculation and output to the DAC are properly synced.
I checked whether an Arduino Duemilanove still works. Seems fine.

ESP32 support (internal and PT8211 DAC)

---

hardware_defines.h
mozzi_config.h

AUDIO_RATE 16384 is a sensible default for the classic Arduino boards, but for the newly added platforms (Teensy3, Arduino Due, STM32, ESP8266, soon ESP32), that does not seem to make a lot of sense.
This PR simply ups that to 32768 on these platforms, while leaving AVR unchanged. With this, there should be a little less need to customize mozzi_config.h with. The PR might affect sketches that are already pushing the stronger boards to the limits, but I think that risk is mostly theoretical.
One point for discussion could might be, whether it would make sense to go even higher, though. Thoughts?

Use higher audio rate by default on faster boards

---

PDResonant.h

Hi,
Reading the doc, I was surprised that it was written there that the PDresonant filter was receiving the frequency of the note as parameter, encoded in `byte`. If I am correct, it actually expect the midi note value.
Not a big change, but can maybe remove some confusion.
Best,
Tom

Changed comments suggesting the pitch being encoded as frequency

---

AudioOutput.h
examples/10.Audio_Filters/LowPassFilterX2/LowPassFilterX2.ino
examples/12.Misc/Stereo_Hack_Pan/Stereo_Hack_Pan.ino

Alongside two non-compiling examples.
Should solve #140 .
Will test now.

FIX `fromAlmostNBits` for 32 bitters

---

MozziGuts_impl_TEENSY.hpp

I don't understand why this was compiling for Teensy 3, but not for Teensy 4. But moving the isr declaration before it is actually referenced do the trick.

Fix compilation for Teensy4

---

MozziGuts_impl_STM32.hpp

After reinstalling Arduino_STM32 to the latest version after a complete reinstallation of my computer, I could not compile Mozzi for STM32. Apparently, the function to attach the ADC interrupt changed. This fixes the compilation here (but I think this would need confirmation from @tfry-git ).
Best,

Fix compilation for STM32_arduino newest version

---

Sample.h

I don't really know why but so far Mozzi use `4294967295UL` to set `endpos_fractional` when no intiable table is provided to the sample. Or the `NUM_TABLE_CELLS` must be anyway provided to build the object. Without this fix, the sample was mess-up.

fix endpos_fractional

---

mozzi_fixmath.h

This commit fixed the documentation to state that a signed 16-bit integer runs from -32768 to 32767.
The existing documentation was probably copied from a 32-bit signed integer.

Updated documentation for Q15n0 with proper limits

---

AudioOutput.h
examples/12.Misc/Stereo_Hack/Stereo_Hack.ino

As said in #159 , Teensy would not compile on `static inline MonoOutput fromNBit` if the sample type is a plain `int` (which is actually the default audio type).
This fixes this problem but I'll wait for a go from @tfry-git to merge this one as I am not sure that multiplying the overloads is actually the good solution.
As for now (without this PR), the example in #159 does not compile on 32bits platforms, but works on AVR.
Best,
Tom

Fix compilation for Teensys

---

AudioConfigRP2040.h
MozziGuts_impl_RP2040.hpp
README.md

Hello and happy new year!
I have started fiddling with the RP2040 (what a nice chip!) and as it does possess I2S support, found a bit sad not to use it in order to interface it with some external DAC. Having a native I2S support allows not to have two buffers in row (Mozzi and the I2S output buffer). Also, it uses DMAs.
A few details:
- there was a IRQ conflict with the implementation of the fast ADC, I add to move the later to IRQ1 instead of IRQ0
- the buffers size are the default ones from the library, maybe it would be worth to have them editable? I am afraid that I'll led the users to input bad configurations actually.
As a draft for now, it seems to work but I want to test it a bit further.
Best,

Added I2S (native) output support for RP2040

---

WaveFolder.h
examples/06.Synthesis/WaveFolder/WaveFolder.ino
keywords.txt

Clean PR for the wavefolder, in response to #153 .
Will test it a bit more extensively and add an example soon.

Added a simple wavefolder

---

README.md

I could not compile sketch with Mozzi for my STM32 black pill (based on STM32F4). After about 2 hours of intense research i found #101 and #89 issues, in which said, that Mozzi is currently not support STM32F4-based boards. I found it useful to put it in README.

Add "STM32F4 is not supported" to README.md

---

StateVariable.h

This fixes #171.
@tfry-git and @sensorium if you comments on the naming please let me know.
Otherwise I'll merge it soon!
Cheers,
Tom

Fix duplicated enum between StateVariable and ResonantFilter

---

.github/workflows/compile_examples.yml
MozziGuts_impl_ESP8266.hpp
examples/02.Control/Line_Gliss/Line_Gliss.ino

This PR is mostly just to make you aware of what I just discovered: It is not so very hard to have automated test builds for all of our boards / examples.
This is still suffering from a few problems, importantly, because not all examples can be compiled for all boards, but looks immensely useful to me, and already helped to find to spot some problems.
See https://github.com/arduino/compile-sketches for more info (would be cool if you could help me bring more boards, and more examples into the builds.)

Add auto-builds for ESP8266

---

MozziGuts.cpp
MozziGuts.h
MozziGuts_impl_MBED.hpp

This is just a small tweak to make EXTERNAL_AUDIO_OUTPUT working. Tested crudefully with a digital output, will try to hook up a real DAC today.
Note: I did not get why I had to change `#if (MBED_AUDIO_OUT_MODE == TIMEDPWM && EXTERNAL_AUDIO_OUTPUT != true)` : I was initially thinking that, as I did not changed the MBED config, `MBED_AUDIO_OUT_MODE == TIMEDPWM` would be false. Shouldn't `AudioConfigMBED.h` be included? I did not go very deep yet.
Let me know if you think me making commits on this branch is not helpful!

Fixed External audio output

---

.github/workflows/compile_examples.yml
AudioConfigMBED.h
MozziGuts.cpp
MozziGuts.h
MozziGuts_impl_ESP8266.hpp
MozziGuts_impl_MBED.hpp
MozziGuts_impl_template.hpp
README.md
extras/NEWS.txt
hardware_defines.h

Initial port of Arduino Giga, essentially made by @tfry-git .
I have checked that both output modes (and external audio output) work fine and added some initial documentation.
I have also inverted the default pins for outputting on the DAC so that mono outputs on the tip of the jack (left) which is the standard.

Initial Arduino Giga port

---

AudioConfigSTM32duino.h
MozziGuts_impl_STM32duino.hpp

Hi!
This fixes the compilation the EXTERNAL_AUDIO_OUTPUT feature for the new the STM port.
Note sure where is the best place to put this declaration though…

Fixed compilation for EXTERNAL_AUDIO_OUTPUT for "new" STM32duino

---

MozziGuts_impl_RENESAS.hpp
MozziGuts_impl_RENESAS_ADC.hpp
README.md

Hi!
This is a proposal for implementing `mozziAnalogRead()` on the Uno R4, following #190.
The result is a bit of a jigsaw puzzle between different source code I could find online (from Arduino, and from Renesas)… There are not a lot of documentation on this chip yet, not to say well documented for people green behind the ears like me…
Anyway, this seems to work quite well. I put the sources inside a separate file because they are not fancy to read but when I look at the final result it might be able to go inside the implementation file. I am up for opinions on this but also on the code in general. I might be doing things a bit naively in there but I had a bit of troubles to make that works in the first place.
I think that when this gets in there it might be time for a new release for the …

Asynchroneous ADC (mozziAnalogRead) for Uno R4

---

.github/workflows/compile_examples.yml

To test, whether this fixes the "report" stage on PR, or whether that breakage is due to something else.

Github workflow: Revert version increas in checkout action

---

MozziGuts_impl_AVR.hpp

Hi,
Fixes #201 by fine tuning the timer frequency. Basically, we get closer to the "ideal" timer frequency by this. Output frequency detuning shifts from 0.25% to 0.06%. To test this, I generated sinusoidal tones in Audacity and listen to the beating when superimposing them to the same tone generated by Mozzi. HiFi is 0.06% off in the native version so I did not touch that.
Untested with external audio, but that should behave the same. Of course, this changes the behavior of all sketches on AVR (but to be closer to reality which I think is fine!) 
Would love to have confirmation from someone else owning an AVR to be sure I am not looking to fix problems with the particular board I am testing with!

Fix frequency offset for AVR

---

Oscil.h

Should optimize slightly for 32bitters.
This is very minor, will merge soon after a bit of extra testing.

Replaced unsigned long into uint32_t for Oscil.

---

FixMath.h

This implements what was discussed in #212 : promoting `NI` of `FixMath` only when needed. 
The approach I am landing now is to keep track of the `RANGE` actually used by the number, initialized to the maximum holdable value by default.
This will probably make heavy use of Macro, because tests will be involved (not available in C++11 constexpr), but that should be a big deal as they are just template parameters which are not used for any calculation.
This draft PR is just to keep an eye on compilations and memory usage automatically.

Implementing auto Range for FixMath

---

learn/porting/index.markdown

This PR fixes link correction for the document:
https://sensorium.github.io/Mozzi/learn/porting/

Fix wrong link destination on porting/index.markdown

---

MetaOscil.h

Fix #282 .
`MetaOscil` went under the radar when adding the support for FixMath. Very simple fix indeed.

Added FixMath support for MetaOscil
